public enum TokenType {
    // Símbolos e operadores
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, DOT, SEMICOLON, COLON, QUESTION,
    PLUS, MINUS, STAR, SLASH, PERCENT,
    PLUS_EQUAL, MINUS_EQUAL, STAR_EQUAL, SLASH_EQUAL, PERCENT_EQUAL,
    BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,
    AND_AND, OR_OR,

    // Literais e identificadores
    IDENTIFIER, STRING, INTERPOLATED_STRING, NUMBER, FLOAT, DOUBLE, CHAR,

    // Palavras-chave
    VAR, INT, FLOAT_KW, DOUBLE_KW, CHAR_KW, BOOL, STRING_KW, TRUE, FALSE,
    IF, ELSE, WHILE, DO, FOR, SWITCH, CASE, DEFAULT, BREAK, CONTINUE, PRINT, INPUT, RETURN, MAIN,

    EOF
}
